app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap


# local imports
from config import app_config


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_pyfile('config.py')
    app.config["FLASK_CONFIG"]="development"
    app.config["FLASK_APP"]="run.py"

    Bootstrap(app)

    # from .home import home as home_blueprint
    # app.register_blueprint(home_blueprint)


    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, render_template, redirect, request
from flask_paginate import Pagination, get_page_parameter

from . import home
from .data import auth, getJson


@home.route('/')
def index():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title = "Welcome")

@home.route('/charts')
def charts():
    """
    Render the charts template
    """
    return render_template("home/charts.html", title = "Charts")

@home.route('/organisations')
def organisations():
    """
    Render the route for organisation units
    """
    # pull organisation units using requests
    organisationUnitsUrl = "https://play.dhis2.org/release1/api/organisationUnits.json?paging=false"
    orgUnits = getJson(organisationUnitsUrl, auth)['organisationUnits'] # get a list of dictionaries

    page = request.args.get(get_page_parameter(), type=int, default=1)

    pagination = Pagination(page=page, per_page=20, total=len(orgUnits), search=True, record_name="Organisation Units")

    return render_template('home/organisations.html', organisation_units=orgUnits, title="Organisation Units", pagination=pagination)

@home.route('/maps')
def maps():
    return redirect('/docs/python/workspace/safi_product/health.html')

@home.route('/elements')
def elements():
    """/docs/python/workspace/safi_product/health.html
    Render the route for data elements
    """
    # pull data elements using requests
    dataElementsUrl = "https://play.dhis2.org/release1/api/dataElements.json?paging=false"
    dataElems = getJson(dataElementsUrl, auth)['dataElements'] # get a list of dictionaries

    return render_template('home/elements.html', title = "Data Elements", data_elements = dataElems)

app/views.py
from flask import abort, render_template, request
from flask_paginate import Pagination, get_page_parameter

from .data import auth, getJson


@app.route('/')
def index():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title = "Welcome")

@app.route('/organisations')
def organisations():
    """
    Render the route for organisation units
    """
    # pull organisation units using requests
    organisationUnitsUrl = "https://play.dhis2.org/release1/api/organisationUnits.json?paging=false"
    orgUnits = getJson(organisationUnitsUrl, auth)['organisationUnits'] # get a list of dictionaries

    page = request.args.get(get_page_parameter(), type=int, default=1)

    pagination = Pagination(page=page, per_page=20, total=len(orgUnits), search=True, record_name="Organisation Units")

    return render_template('home/organisations.html', organisation_units=orgUnits, title="Organisation Units", pagination=pagination)

@app.route('/elements')
def elements():
    """
    Render the route for data elements
    """
    # pull data elements using requests
    dataElementsUrl = "https://play.dhis2.org/release1/api/dataElements.json?paging=false"
    dataElems = getJson(dataElementsUrl, auth)['dataElements'] # get a list of dictionaries

    return render_template('home/elements.html', title = "Data Elements", data_elements = dataElems)

app/templates/home/charts.html
{% import "bootstrap/utils.html" as utils %}
{% extends "layout.html" %}
{% block title %}Charts{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <br/>
    {{ utils.flashed_messages() }}
    <br/>
    <h1 style="text-align:center;">Charts</h1>
    <br>
    <br>
    <div class="center layer">
      <h1>Bar Graph Maternal Visits</h1>
      <canvas id="maternal" width="800" height="450"></canvas>
      <br><br><br><br><br>
      <h1>Line Graph Maternal Visits</h1>
      <canvas id="maternal_line" width="800" height="450"></canvas>
      <br><br><br><br><br>
      <canvas id="myChart" width="800" height="450"></canvas>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/elements.html
{% import "bootstrap/utils.html" as utils %}
{% extends "layout.html" %}
{% block title %}Organisation Units{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Data Elements</h1>
        {% if data_elements %}
          <hr class="intro-divider">
          <div class="center">
            <form class="form-inline">
              <div class="form-group">
                <label for="">Search by id</label>
                <input type="text" class="form-control" id="by_id" name="id" placeholder="Search by Id">
              </div>
              <div class="form-group">
                <label for="name">Search by name</label>
                <input type="text" class="form-control" id="by_name" name="name" placeholder="Search by Name">
              </div>
            </form>
            <br>
            <table id="myTable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="10%"></th>
                  <th width="20%"> Id </th>
                  <th width="70%"> Data Elements </th>
                </tr>
              </thead>
              <tbody>
              {% for element in data_elements %}
                <tr>
                  <td>{{ data_elements.index(element) +1 }}</td>
                  <td> {{ element['id'] }} </td>
                  <td> {{ element['displayName'] }} </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No Data Elements have been found. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Data Element
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">
          <h1>DHIS Hackathon</h1>
          <blockquote cite="">
            <h3>Clinovation</h3>
          </blockquote>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/organisations.html
{% import "bootstrap/utils.html" as utils %}
{% extends "layout.html" %}
{% block title %}Organisation Units{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Organisation Units</h1>
        {% if organisation_units %}
          <hr class="intro-divider">
          <div class="center">
            <form class="form-inline">
              <div class="form-group">
                <label for="">Search by id</label>
                <input type="text" class="form-control" id="by_id" name="id" placeholder="Search by Id">
              </div>
              <div class="form-group">
                <label for="name">Search by name</label>
                <input type="text" class="form-control" id="by_name" name="name" placeholder="Search by Name">
              </div>
            </form>
            <br>
            <table id="myTable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="10%"></th>
                  <th width="30%"> Unique id </th>
                  <th width="60%"> Organisation Units </th>
                </tr>
              </thead>
              <tbody>
              {% for org in organisation_units %}
                <tr>
                  <td> {{ organisation_units.index(org) + 1}} </td>
                  <td> {{ org['id'] }} </td>
                  <td> {{ org['displayName'] }} </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No Organisation units have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Organisation Unit
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/presentations.html
{% import "bootstrap/utils.html" as utils %}
{% extends "layout.html" %}
{% block title %}Immunisation{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Immunisation</h1>
        {% if immunisation %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="30%"> Id </th>
                  <th width="70%"> Immunisation </th>
                </tr>
              </thead>
              <tbody>
              {% for disease in immunisation %}
                <tr>
                  <td> {{ disease['id'] }} </td>
                  <td> {{ disease['displayName'] }} </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No Organisation units have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Organisation Unit
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ title }} | HIGDA - DHIS </title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/scripts.js') }}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
      <div class="container topnav">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand topnav" href="{{ url_for('home.index') }}">Hello Life</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('home.charts') }}">Charts</a></li>
            <li><a href="{{ url_for('home.elements') }}">Data Elements</a></li>
            <li><a href="{{ url_for('home.organisations') }}">Organisation Units</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
  </body>
</html>